// <auto-generated />
using System;
using ECommerceApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerceApi.Migrations
{
    [DbContext(typeof(ECommerceDbContext))]
    [Migration("20260505192610_UpdateProductImageUrls")]
    partial class UpdateProductImageUrls
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ECommerceApi.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CanceledDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeliveredDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LastModified = new DateTime(2026, 5, 5, 19, 26, 10, 466, DateTimeKind.Utc).AddTicks(4260),
                            OrderDate = new DateTime(2026, 4, 30, 19, 26, 10, 466, DateTimeKind.Utc).AddTicks(4264),
                            ShippedDate = new DateTime(2026, 5, 1, 19, 26, 10, 466, DateTimeKind.Utc).AddTicks(4273),
                            Status = "Shipped",
                            TotalAmount = 1339.98m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DeliveredDate = new DateTime(2026, 5, 3, 19, 26, 10, 466, DateTimeKind.Utc).AddTicks(4281),
                            LastModified = new DateTime(2026, 5, 5, 19, 26, 10, 466, DateTimeKind.Utc).AddTicks(4278),
                            OrderDate = new DateTime(2026, 4, 25, 19, 26, 10, 466, DateTimeKind.Utc).AddTicks(4279),
                            ShippedDate = new DateTime(2026, 4, 26, 19, 26, 10, 466, DateTimeKind.Utc).AddTicks(4280),
                            Status = "Delivered",
                            TotalAmount = 449.99m,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("ECommerceApi.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 1,
                            UnitPrice = 1299.99m
                        },
                        new
                        {
                            Id = 2,
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 29.99m
                        },
                        new
                        {
                            Id = 3,
                            OrderId = 2,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 449.99m
                        });
                });

            modelBuilder.Entity("ECommerceApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 5, 19, 26, 10, 466, DateTimeKind.Utc).AddTicks(3893),
                            Description = "High-performance laptop",
                            ImageUrl = "/images/laptop.jpg",
                            Name = "Laptop Pro",
                            Price = 1299.99m,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 5, 19, 26, 10, 466, DateTimeKind.Utc).AddTicks(3906),
                            Description = "Ergonomic wireless mouse",
                            ImageUrl = "/images/wireless_mouse.jpg",
                            Name = "Wireless Mouse",
                            Price = 29.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 5, 19, 26, 10, 466, DateTimeKind.Utc).AddTicks(3908),
                            Description = "Fast charging USB-C cable",
                            ImageUrl = "/images/usb_cable.jpg",
                            Name = "USB-C Cable",
                            Price = 9.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 5, 19, 26, 10, 466, DateTimeKind.Utc).AddTicks(3909),
                            Description = "27-inch 4K monitor",
                            ImageUrl = "/images/monitor.jpg",
                            Name = "Monitor 4K",
                            Price = 449.99m,
                            StockQuantity = 8
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 5, 5, 19, 26, 10, 466, DateTimeKind.Utc).AddTicks(3910),
                            Description = "RGB mechanical gaming keyboard",
                            ImageUrl = "/images/mechanical_keyboard.jpg",
                            Name = "Mechanical Keyboard",
                            Price = 149.99m,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 5, 5, 19, 26, 10, 466, DateTimeKind.Utc).AddTicks(3917),
                            Description = "1080p HD webcam with mic",
                            ImageUrl = "/images/webcam.jpg",
                            Name = "Webcam HD",
                            Price = 79.99m,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 5, 5, 19, 26, 10, 466, DateTimeKind.Utc).AddTicks(3918),
                            Description = "LED desk lamp with USB charging",
                            ImageUrl = "/images/desk_lamp.jpg",
                            Name = "Desk Lamp",
                            Price = 39.99m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 5, 5, 19, 26, 10, 466, DateTimeKind.Utc).AddTicks(3919),
                            Description = "Adjustable phone stand",
                            ImageUrl = "/images/phone_stand.jpg",
                            Name = "Phone Stand",
                            Price = 14.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 5, 5, 19, 26, 10, 466, DateTimeKind.Utc).AddTicks(3920),
                            Description = "1TB portable SSD",
                            ImageUrl = "/images/ssd.jpg",
                            Name = "Portable SSD",
                            Price = 129.99m,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 5, 5, 19, 26, 10, 466, DateTimeKind.Utc).AddTicks(3922),
                            Description = "Noise-cancelling wireless headphones",
                            ImageUrl = "/images/headphone.jpg",
                            Name = "Headphones",
                            Price = 199.99m,
                            StockQuantity = 12
                        });
                });

            modelBuilder.Entity("ECommerceApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 5, 19, 26, 10, 466, DateTimeKind.Utc).AddTicks(3278),
                            Email = "john@example.com",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 5, 19, 26, 10, 466, DateTimeKind.Utc).AddTicks(3282),
                            Email = "jane@example.com",
                            Name = "Jane Smith"
                        });
                });

            modelBuilder.Entity("ECommerceApi.Models.Order", b =>
                {
                    b.HasOne("ECommerceApi.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ECommerceApi.Models.OrderItem", b =>
                {
                    b.HasOne("ECommerceApi.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerceApi.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECommerceApi.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ECommerceApi.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ECommerceApi.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
